---
- name: setuo all hosts
  hosts: all
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  vars:
   administrator_name: corpadmin
  tasks:
  - name: update all currents packages
    yum: name='*' state=latest
  - name: create administrator_name user
    user: name={{ administrator_name }} password=123456


- name: setups web1
  hosts: web1
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  tasks:
  - name: install nginx
    yum: name=nginx state=latest
  - name: copy default.conf.j2 template
    template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  - name: make sure nginx is starting
    service: name=nginx state=started enabled=yes

- name: database1 setup
  hosts: database1
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  tasks:
  - name: install mysql
    yum: name=mysql-server state=latest
  - name: making sure mysql is running
    service: name=mysqld state=started enabled=yes
  - name: creating 5 directories
    file: path=/var/data/client{{ item }} state=directory
    with_sequence: start=1 end=5 stride=1
